apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhooks
  namespace: after-hours-scaler
spec:
  secretStoreRef:
    name: aws-global
    kind: ClusterSecretStore
  data:
    - secretKey: PLATFORM_ALERTS
      remoteRef:
        key: some/aws/secret
        property: platform-alerts
  target:
    name: slack-webhooks
    creationPolicy: Owner
