# Service account is created via the eks-module
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: after-hours-scaler
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: ["karpenter.sh"]
  resources: ["nodepools"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: after-hours-scaler
subjects:
- kind: ServiceAccount
  name: after-hours-scaler
  namespace: after-hours-scaler
roleRef:
  kind: ClusterRole
  name: after-hours-scaler
  apiGroup: rbac.authorization.k8s.io
